//
// Generated file, do not edit! Created by nedtool 4.6 from TCPPkt_m.msg.
//

#ifndef _TCPPKT_M_M_H_
#define _TCPPKT_M_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "NetPkt_m.h"
// }}

/**
 * Class generated from <tt>TCPPkt_m.msg:27</tt> by nedtool.
 * <pre>
 * //
 * // Message class for representing a Telnet packet (bytes carried in TCP).
 * // For purposes of this model, we don't care about TCP connection setup
 * // and teardown, about TCP acks, or finite IP packet size.
 * //
 * packet TCPPkt extends NetPkt
 * {
 *     string payload;
 * }
 * </pre>
 */
class TCPPkt : public ::NetPkt
{
  protected:
    opp_string payload_var;

  private:
    void copy(const TCPPkt& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TCPPkt&);

  public:
    TCPPkt(const char *name=NULL, int kind=0);
    TCPPkt(const TCPPkt& other);
    virtual ~TCPPkt();
    TCPPkt& operator=(const TCPPkt& other);
    virtual TCPPkt *dup() const {return new TCPPkt(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getPayload() const;
    virtual void setPayload(const char * payload);
};

inline void doPacking(cCommBuffer *b, TCPPkt& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TCPPkt& obj) {obj.parsimUnpack(b);}


#endif // ifndef _TCPPKT_M_M_H_

